[project]
name = "git-ssh-key"
version = "0.1.1-a1"
description = ""
dependencies = [ "sshconf>=0.2.4", "click>=8.0.3", "giturlparse>=0.10.0",]
requires-python = ">=3.8"
readme = "README.md"
[[project.authors]]
name = "alingse"
email = "alingse@foxmail.com"

[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/alingse/git-ssh-key"

[project.scripts]
git-ssh-key = "gitsshkey.main:main"

[tool.pdm]
