[tool.poetry]
name = "MathPrimes"
version = "1.0.2"
description = "Well documented, super fast, prime number methods using mathematical algorithms."
authors = ["GrandMoff100 <nlarsen23.student@gmail.com>"]
license = "MIT"
repository = "https://github.com/GrandMoff100/MathPrimes"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
