[tool.poetry]
name = "levo"
version = "0.4.8"
description = "Levo.ai's CLI that users can use to automatically trigger functional and security testing of their APIs."
authors = ["Buchi Reddy B <buchi@levo.ai>"]
packages = [
    { include = "levocli", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0"
requests = "^2.25.1"
schemathesis = "3.11.7"
grpcio = "^1.37.0"
reportportal-client = "^5.1.0"
protobuf = "^3.15.8"
colorama = "^0.4.4"
sgqlc = "^14.0"
pydantic = "^1.8.2"
questionary = "^1.10.0"
structlog = "^21.4.0"
click-loglevel = "^0.4.0"
envyaml = "^1.10.211231"
betterproto = {version = "^2.0.0b3", allow-prereleases = true}
jsonpath-ng = "^1.5.3"
cryptography = "^36.0.1"
yamlordereddictloader = "^0.4.0"
cattrs = "^1.9.0"
orjson = "^3.6.5"
"python-owasp-zap-v2.4" = "^0.0.19"
"docker" = "^5.0.3"

# Levo specific dependencies
levo-commons = "0.1.27"
levo-ssrfmap = "^0.1.12"
rich = "^11.0.0"

[tool.poetry.dev-dependencies]
grpcio-tools = "^1.38.0"
pytest-cov = "^3.0.0"
pytest-httpserver = "^1.0.3"

[tool.poetry.scripts]
levo = "levocli.cli:levo"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
