[tool.coverage.paths]
source=["src","*/site-packages"]

[tool.coverage.run]
branch=true
source=["dataverk_publisher"]

[tool.coverage.report]
show_missing=true

[tool.poetry]
name = 'dataverk-publisher'
version = '0.0.8'
description = ""
authors = ["erikvatt <erik.vattekar@nav.no>"]

[tool.poetry.dependencies]
python = "^3.6.8"
deetly = "^0.0.26"
requests = "^2.24.0"
google-cloud-storage = "^1.40.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
